all: TCPEnd.class

TCPEnd.class: TCPEnd.java TCPEndHost.java GBNSegment.java Sender.java Receiver.java HandshakeType.java MaxRetransmitException.java SegmentChecksumMismatchException.java UnexpectedFlagException.java
	javac $^