all: TCPEnd.class

TCPEnd.class: src/TCPEnd.java src/TCPEndHost.java src/GBNSegment.java src/Sender.java src/Receiver.java src/HandshakeType.java src/MaxRetransmitException.java src/SegmentChecksumMismatchException.java src/UnexpectedFlagException.java
	javac $^