all: src/TCPEnd.class

src/TCPEnd.class: src/TCPEnd.java src/TCPEndHost.java src/GBNSegment.java src/Sender.java src/Receiver.java src/HandshakeType.java src/MaxRetransmitException.java src/SegmentChecksumMismatchException.java src/UnexpectedFlagException.java
	cd src; javac -g TCPEnd.java